---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Song.
--- DateTime: 2024/5/28 下午12:10
---

require('LuaPanda').start("localhost", 8818)
require('emmy_core').tcpListen('localhost', 9966)