---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/21 20:19
---
require("Manager.BagManager")

local Define = {
    LoginSystem = require("System.LoginSystem"),
    TimeSystem = require("System.TimeSystem"),
}

return Define