---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/21 20:19
---

local SystemKeys = {
    "DataSystem",
    "EventSystem",
    "LoginSystem",
    "NetworkSystem",
    "PanelSystem",
    "RoleSystem",
    "TimeSystem",
    "WorldSystem",
}

local ManagerKeys = {
    "BagManager",
}

local Env = {
    Systems = {},
    Managers = {},
}

for _, SystemKey in ipairs(SystemKeys) do
    local System = require("System."..SystemKey)
    if System.Initialize then
        System:Initialize()
    end
    Env.Systems[SystemKey] = System
end

for _, ManagerKey in ipairs(ManagerKeys) do
    local Manager = require("Manager."..ManagerKey)
    if Manager.Initialize then
        Manager:Initialize()
    end
    Env.Managers[ManagerKey] = Manager
end

return Env