---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/21 20:19
---

local Env = {
    EventSystem = require("System.EventSystem"),
    LoginSystem = require("System.LoginSystem"),
    TimeSystem = require("System.TimeSystem"),
    NetworkSystem = require("System.NetworkSystem"),
    RoleSystem = require("System.RoleSystem"),
    PanelSystem = require("System.PanelSystem"),
}

Env.Managers = {
    "BagManager",
}

return Env