---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/21 20:19
---

local Systems = {
    "EventSystem",
    "LoginSystem",
    "TimeSystem",
    "NetworkSystem",
    "RoleSystem",
    "PanelSystem",
    "WorldSystem",
}

local Managers = {
    "BagManager",
}


local Env = {}

for _, SystemKey in ipairs(Systems) do
    Env[SystemKey] = require("System."..SystemKey)
end
for _, ManagerKey in ipairs(Managers) do
    require("Manager."..ManagerKey)
end

return Env