---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/17 16:53
---

_G.Class = require("Utils.Class")
_G.Handler = require("Utils.Handler")

_G.EventSystem = require("Utils.Event")()