---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/27 11:32
---

local Enum = {
    PanelEnum = {
        Main = 1,
        Login = 2,
    },
    JumpPanelEnum = {
        Main = 1,
        Login = 2,
    }
}

return Enum