---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/27 11:37
---

local JumpPanelTable = {
    [1] = {
        PanelKey = 1,
        Params = {1, 2, 3}
    },
    [2] = {
        PanelKey = 2,
        Params = {}
    }
}

return JumpPanelTable