---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/27 11:28
---

---@class PanelTable
local PanelTable = {
    [1] = {
        Blueprint = "Class'/Game/Demo/UMG/Main/Panel_Main.Panel_Main_C'",
        ZOrder = 0,
    },
    [2] = {
        Blueprint = "Class'/Game/Demo/UMG/Login/Panel_Login.Panel_Login_C'",
        ZOrder = 0,
    }
}

return PanelTable