---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/21 14:42
---

local setmetatable = setmetatable

local ObjectIndex = function(Object, Index)
    local Class = Object.Class
    while(Class)
    do
        local Value = Class[Index]
        if Value then
            return Value
        else
            Class = Class.Super
        end
    end
end

local ClassCall = function(Class, ...)
    local Object = {
        Class = Class
    }
    setmetatable(Object, {__index = ObjectIndex})
    if Object.Ctor then
        Object:Ctor(...)
    end
    return Object
end

---@param Super Class
local ClassFunc = function(Super)
    ---@class Class
    ---@field Ctor fun(self: table, ...)
    local Class = {
        Super = Super
    }
    setmetatable(Class, {__call = ClassCall})
    return Class
end

return ClassFunc