---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/21 17:30
---

local ipairs = ipairs
local setmetatable = setmetatable

local HandlerCall = function(Handler, ...)
    local bCompare = true
    local Params = {...}
    for Index, Param in ipairs(Handler.Params) do
        if Params[Index] ~= Param then
            bCompare = false
            break
        end
    end
    if bCompare then
        Handler.Function(Handler.Object, ...)
    end
end

local HandlerFunc = function(Object, Function, ...)
    ---@class Handler
    local Handler = {
        Object = Object,
        Function = Function,
        Params = {...}
    }
    setmetatable(Handler, {__call = HandlerCall})
    return Handler
end

return HandlerFunc