---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/21 20:02
---

local RoleSystem = require("System.RoleSystem")

---@class Manager
local Manager = Class()


local ManagerFunc = function(Name)
    local ChildManager = Class(Manager)
    RoleSystem:RegisterManager(Name, ChildManager)
    return ChildManager
end

return ManagerFunc