---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/27 19:35
---

local setmetatable = setmetatable

---@class ManagerBase
local ManagerBase = {}

function ManagerBase:Initialize() end

local CreateManager = function()
    ---@class Manager : ManagerBase
    local Manager = {}
    setmetatable(Manager, ManagerBase)
    return Manager
end

return CreateManager