---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/27 19:28
---

local setmetatable = setmetatable

---@class SystemBase
local SystemBase = {}

function SystemBase:Initialize() end

local CreateSystem = function()
    ---@class System : SystemBase
    local System = {}
    setmetatable(System, SystemBase)
    return System
end

return CreateSystem