---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/24 11:12
---

---@type UByUserWidget
local Widget = UnLua.Class()

function Widget:OnOpen(...)

end

function Widget:OnUpdate(...)

end

function Widget:OnClose()

end

function Widget:Close()

end

return Widget