---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/24 11:12
---

local PanelSystem = require("System.PanelSystem")

---@type UByUserWidget
local Widget = UnLua.Class()

function Widget:OnOpen(...) end

function Widget:OnUpdate(...) end

function Widget:Close()

end

function Widget:OpenPanel(PanelKey, ...)
    PanelSystem:OpenPanel(PanelKey, ...)
end

function Widget:ClosePanel(PanelKey)
    PanelSystem:ClosePanel(PanelKey)
end

return Widget