---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/21 14:45
---

local Handler = Handler
local pairs = pairs

---@class EventSystem
local EventSystem = {
    _EventDict = {}
}

---Register
---注册事件
---@param EventName string
---@param Object table
---@param Function function
function EventSystem:Register(EventName, Object, Function, ...)
    local EventDict = self._EventDict[Object]
    if not EventDict then
        EventDict = {}
        self._EventDict[EventName] = EventDict
    end
    local HandlerDict = EventDict[EventName]
    if not HandlerDict then
        HandlerDict = {}
        EventDict[EventName] = HandlerDict
    end
    HandlerDict[Function] = Handler(Object, Function, ...)
end

---UnRegister
---@param EventName string
---@param Object table
---@param Function function
function EventSystem:UnRegister(EventName, Object, Function)
    local EventDict = self._EventDict[Object]
    if EventDict then
        local HandlerDict = EventDict[EventName]
        if HandlerDict then
            HandlerDict[Function] = nil
        else
            EventDict[EventName] = nil
        end
    else
        self._EventDict = {}
    end
end

---UnRegisterWithObject
---@param Object table
function EventSystem:UnRegisterWithObject(Object)
    self._EventDict[Object] = nil
end

---Broadcast
---@param EventName string
function EventSystem:Broadcast(EventName, ...)
    local EventDict = self._EventDict[EventName]
    if EventDict then
        for _, HandlerDict in pairs(EventDict) do
            for _, HandlerObject in pairs(HandlerDict) do
                HandlerObject(...)
            end
        end
    end
end

return EventSystem