---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/21 14:45
---

local Handler = Handler
local pairs = pairs

---@class EventSystem
local EventSystem = {
    _EventDict = {},
    _NamesDict = {}
}

---Register
---注册事件
---@param EventName string
---@param Object table
---@param Function function
function EventSystem:Register(EventName, Object, Function, ...)
    local ObjectDict = self._EventDict[EventName]
    if not ObjectDict then
        ObjectDict = {}
        self._EventDict[EventName] = ObjectDict
    end
    local HandlerDict = ObjectDict[Object]
    if not HandlerDict then
        HandlerDict = {}
        ObjectDict[Object] = HandlerDict
    end
    HandlerDict[Function] = Handler(Object, Function, ...)

    local NameDict = self._NamesDict[Object]
    if not NameDict then
        NameDict = {}
        self._NamesDict[Object] = NameDict
    end
    NameDict[EventName] = Object
end

---UnRegister
---@param EventName string
---@param Object table
---@param Function function
function EventSystem:UnRegister(EventName, Object, Function)
    local ObjectDict = self._EventDict[EventName]
    if ObjectDict then
        local NameDict = self._NamesDict[Object]
        if NameDict then
            NameDict[EventName] = nil
        end
        local HandlerDict = ObjectDict[Object]
        if HandlerDict then
            HandlerDict[Function] = nil
        end
    end
end

---UnRegisterWithObject
---@param Object table
function EventSystem:UnRegisterWithObject(Object)
    local NameDict = self._NamesDict[Object]
    if NameDict then
        for EventName, _ in pairs(NameDict) do
            self:UnRegister(EventName, Object)
        end
    end
end

---Broadcast
---@param EventName string
function EventSystem:Broadcast(EventName, ...)
    local EventDict = self._EventDict[EventName]
    if EventDict then
        for _, HandlerDict in pairs(EventDict) do
            for _, HandlerObject in pairs(HandlerDict) do
                HandlerObject(...)
            end
        end
    end
end

return EventSystem