---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/21 14:45
---

local Handler = Handler
local pairs = pairs
local next = next

---@class EventSystem
local EventSystem = {
    _EventMap = {},
    _ObjectMap = {}
}

---Register
---注册事件
---@param EventKey number
---@param Object table
---@param Function function
function EventSystem:Register(EventKey, Object, Function, ...)
    if not EventKey or not Object or not Function then
        return
    end

    local ObjectDict = self._EventMap[EventKey]
    if not ObjectDict then
        ObjectDict = {}
        self._EventMap[EventKey] = ObjectDict
    end
    local HandlerDict = ObjectDict[Object]
    if not HandlerDict then
        HandlerDict = {}
        ObjectDict[Object] = HandlerDict
    end
    HandlerDict[Function] = Handler(Object, Function, ...)

    local KeyDict = self._ObjectMap[Object]
    if not KeyDict then
        KeyDict = {}
        self._ObjectMap[Object] = KeyDict
    end
    KeyDict[EventKey] = Object
end

---UnRegister
---@param EventKey number
---@param Object table
---@param Function function
function EventSystem:UnRegister(EventKey, Object, Function)
    if not EventKey or not Object then
        return
    end

    local Clear = false
    local ObjectDict = self._EventMap[EventKey]
    if ObjectDict then
        if Function then
            local HandlerDict = ObjectDict[Object]
            if HandlerDict then
                HandlerDict[Function] = nil
            end
            if not next(HandlerDict) then
                Clear = true
            end
        else
            Clear = true
        end

        ObjectDict[Object] = nil
        if not next(ObjectDict[Object]) then
            self._EventMap[EventKey] = nil
        end
        local KeyDict = self._ObjectMap[Object]
        if KeyDict then
            KeyDict[EventKey] = nil
            if not next(KeyDict) then
                self._ObjectMap[Object] = nil
            end
        end
    end
end

---UnRegisterWithObject
---@param Object table
function EventSystem:UnRegisterWithObject(Object)
    local KeyDict = self._ObjectMap[Object]
    if KeyDict then
        for EventKey, _ in pairs(KeyDict) do
            self:UnRegister(EventKey, Object)
        end
    end
end

---Broadcast
---@param EventKey number
function EventSystem:Broadcast(EventKey, ...)
    print("EventSystem:Broadcast", EventKey)
    local EventDict = self._EventMap[EventKey]
    if EventDict then
        for _, HandlerDict in pairs(EventDict) do
            for _, HandlerObject in pairs(HandlerDict) do
                HandlerObject(...)
            end
        end
    end
end

return EventSystem