---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/21 14:52
---

---@class NetworkSystem : System
local NetworkSystem = System()

return NetworkSystem