---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/24 11:02
---

---@class PanelSystem
local PanelSystem = {
    _PanelDict = {},
    _PanelStack = {}
}

function PanelSystem:EnterWorld(WorldName)
    print("PanelSystem:EnterWorld", WorldName)
end

function PanelSystem:OpenPanel(PanelKey, ...)

end

function PanelSystem:ClosePanel(PaneKey)

end

function PanelSystem:CloseAll()

end

return PanelSystem