---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/24 15:34
---

local PanelSystem = require("System.PanelSystem")

---@class WorldSystem
local WorldSystem = {}

function WorldSystem:OnPostWorldInitialization(WorldName)
    PanelSystem:EnterWorld(WorldName)
end

return WorldSystem