---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/24 15:34
---

local PanelSystem = require("System.PanelSystem")

---@class WorldSystem : System
local WorldSystem = System()

---OnPostWorldInitialization
---@param World UWorld
function WorldSystem:OnWorldBeginPlay(World, WorldName)
    _G.World = World

    PanelSystem:EnterWorld(WorldName)
end

return WorldSystem