---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/24 11:37
---

---@class Panel_Main : UByUserWidget
local Panel_Main = UnLua.Class("Util.Widget")

function Panel_Main:Construct()
    print("Panel_Main:Construct()")
end

function Panel_Main:OnOpen()
    print("Panel_Main:OnOpen()")
end

return Panel_Main