---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/24 11:37
---

---@type Panel_Main_C
local Panel_Main_C = UnLua.Class("Util.Widget")

function Panel_Main_C:Construct()
    print("Panel_Main_C:Construct()")
end

function Panel_Main_C:OnOpen()
    print("Panel_Main_C:OnOpen()")
end

return Panel_Main_C