---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by byteyang.
--- DateTime: 2023/11/27 17:23
---

---@type Panel_Login_C
local Panel_Login_C = UnLua.Class("Util.Widget")

function Panel_Login_C:Construct()

end

function Panel_Login_C:OnOpen()

end

return Panel_Login_C
